source.. = src/main/java/
output.. = target/classes
bin.includes = META-INF/,\
               .,\
               plugin.xml
bin.excludes = pom.xml,\
               .classpath,\
               .project,\
               .settings/
